setup_travis
# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

app_version = '1.0'

platform :ios do

  before_all do
    scan(scheme:"ToDo", project:"ToDo.xcodeproj")
  end

  desc "Description of what the lane does"
  lane :beta do
    # add actions here: https://docs.fastlane.tools/actions
  end
end
